### PR TITLE
fix popup auth broken due to new COOP header

### LINKED ISSUE #137: osm-auth example fails unless "single page" is selected
The [osm-auth example](https://osmlab.github.io/osm-auth/) fails silently unless the single page checkbox is selected.
```
Uncaught TypeError: can't access property "authComplete", opener is null
```
due to https://github.com/openstreetmap/openstreetmap-website/commit/2ff4d6a4e633e479568572090eb6a16074103cd9 ?

### PR DESCRIPTION
**Pull request by k-yle**
Caused by https://github.com/openstreetmap/openstreetmap-website/commit/2ff4d6 , Closes #137

[`window.opener`](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) can't be used anymore, so we have to use a [`BroadcastChannel`](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) instead. [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel)s only support comms within [the same origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), so this shouldn't introduce any new security risks in comparison to the existing solution, to the best of my knowledge. 

This is a breaking change because users need to manually update their `land.html` file.

Unfortunately, this also reverts #135, which isn't possible anymore, since the popup window sets a restrictive [COOP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cross-Origin-Opener-Policy)

### CODE REVIEW

**Comment by bhousel** [comment]
Well this is the first I'm hearing about it.  
I'll have to give a big change like this a proper review.

File: dist/osm-auth.cjs [hunk 1]
```diff
@@ -172,8 +165,11 @@ function osmAuth(o) {
         return;
       }
       _getAccessToken(params2.code, pkce.code_verifier, accessTokenDone);
-      delete window.authComplete;
-    };
+      bc.removeEventListener("message", onMessage);
+      bc.close();
+    }
+    ;
```
Comment (tordans) [inline dist/osm-auth.cjs:171]:
```suggestion
    };
```

Comment (k-yle) [reply dist/osm-auth.cjs:171]: this is actually a compiled `dist/` file, so the formatting was esbuild's idea not mine 😅 

(for more active repos i'd suggest [marking files like this as `linguist-generated`](https://github.com/home-assistant/core/blob/87b00fdc7ba4fae70b1ab91f95c4226caadcae61/.gitattributes#L15-L24) so that [they're hidden from the PR diff](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) by default)

File: src/osm-auth.mjs [hunk 2]
```diff
@@ -261,8 +257,10 @@ export function osmAuth(o) {
         return;
       }
       _getAccessToken(params.code, pkce.code_verifier, accessTokenDone);
-      delete window.authComplete;
+      bc.removeEventListener('message', onMessage);
```
Comment (1ec5) [inline src/osm-auth.mjs:260]: I think it might be safe to close the broadcast channel without explicitly removing the event listener. That would allow you to turn this function into a closure.

**Review by 1ec5 — COMMENTED** [review]
I’ve only used `BroadcastChannel` on occasion, but this looks about right to me.

**Comment by HarelM** [comment]
How do you know if the popup window was closed by the user after this change?
Here's a similar comment I added to the change made in OSM:
https://github.com/openstreetmap/openstreetmap-website/commit/2ff4d6a4e633e479568572090eb6a16074103cd9#commitcomment-161835429

Any insight would be helpful. Thanks!

**Comment by k-yle** [comment]
> How do you know if the popup window was closed by the user after this change?

Correct me if I'm wrong, but the [COOP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cross-Origin-Opener-Policy) intentionally makes this impossible, hence why this PR also reverts #135 🫤 

This also prevents a dodgy referrer from polling [`Window#closed`](https://developer.mozilla.org/en-US/docs/Web/API/Window/closed) to track how longer the user spends in a new tab

**Comment by jjiglesiasg** [comment]
HOW THIS COULD BE SOLVED?, THERE IS NO POSSIBLE TO LOG IN
